# Goal definition: Distance to travel while seeking. Set to +/- INT_MAX when seeking to the end.
float32 distance
---

# Result definition: Status code of the action, and the RFID identifier
int8 status
float32 position

---

# No feedback message, current implementation by ROS is redundant


